"""initial schema

Revision ID: 11faf7b6125d
Revises: 
Create Date: 2026-07-15 10:50:29.412848
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11faf7b6125d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_id')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_table('consolidation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('request_options', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consolidation_jobs_organization_id'), 'consolidation_jobs', ['organization_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_index(op.f('ix_templates_organization_id'), 'templates', ['organization_id'], unique=False)
    op.create_table('consolidated_workbooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consolidation_job_id', sa.String(length=36), nullable=False),
    sa.Column('stored_key', sa.String(length=700), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consolidation_job_id'], ['consolidation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_key')
    )
    op.create_index(op.f('ix_consolidated_workbooks_consolidation_job_id'), 'consolidated_workbooks', ['consolidation_job_id'], unique=True)
    op.create_table('countries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_index(op.f('ix_countries_organization_id'), 'countries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_countries_template_id'), 'countries', ['template_id'], unique=False)
    op.create_table('template_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('mapping_version', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_key', sa.String(length=700), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sheet_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('workbook_metadata', sa.JSON(), nullable=False),
    sa.Column('imported_by_id', sa.String(length=36), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_key'),
    sa.UniqueConstraint('template_id', 'version')
    )
    op.create_index(op.f('ix_template_versions_sha256'), 'template_versions', ['sha256'], unique=False)
    op.create_index(op.f('ix_template_versions_template_id'), 'template_versions', ['template_id'], unique=False)
    op.create_table('country_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_files_country_id'), 'country_files', ['country_id'], unique=False)
    op.create_table('sheet_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_version_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_index', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('max_row', sa.Integer(), nullable=False),
    sa.Column('max_column', sa.Integer(), nullable=False),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('mapping_status', sa.String(length=40), nullable=False),
    sa.Column('merged_ranges', sa.JSON(), nullable=False),
    sa.Column('formula_cells', sa.JSON(), nullable=False),
    sa.Column('native_tables', sa.JSON(), nullable=False),
    sa.Column('named_ranges', sa.JSON(), nullable=False),
    sa.Column('structural_signature', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_version_id', 'name')
    )
    op.create_index(op.f('ix_sheet_definitions_template_version_id'), 'sheet_definitions', ['template_version_id'], unique=False)
    op.create_table('country_file_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_file_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_key', sa.String(length=700), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('workbook_metadata', sa.JSON(), nullable=False),
    sa.Column('imported_by_id', sa.String(length=36), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_file_id'], ['country_files.id'], ),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_file_id', 'version'),
    sa.UniqueConstraint('stored_key')
    )
    op.create_index(op.f('ix_country_file_versions_country_file_id'), 'country_file_versions', ['country_file_id'], unique=False)
    op.create_index(op.f('ix_country_file_versions_sha256'), 'country_file_versions', ['sha256'], unique=False)
    op.create_table('table_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sheet_definition_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('range_ref', sa.String(length=60), nullable=False),
    sa.Column('header_rows', sa.JSON(), nullable=False),
    sa.Column('data_start_row', sa.Integer(), nullable=False),
    sa.Column('data_end_row', sa.Integer(), nullable=True),
    sa.Column('data_end_rule', sa.JSON(), nullable=True),
    sa.Column('key_columns', sa.JSON(), nullable=False),
    sa.Column('value_columns', sa.JSON(), nullable=False),
    sa.Column('total_rows', sa.JSON(), nullable=False),
    sa.Column('computed_columns', sa.JSON(), nullable=False),
    sa.Column('structure_mode', sa.String(length=30), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('variable_rows', sa.JSON(), nullable=False),
    sa.Column('variable_columns', sa.JSON(), nullable=False),
    sa.Column('ignored_rows', sa.JSON(), nullable=False),
    sa.Column('ignored_columns', sa.JSON(), nullable=False),
    sa.Column('required_cells', sa.JSON(), nullable=False),
    sa.Column('required_formulas', sa.JSON(), nullable=False),
    sa.Column('tolerate_blank_rows_columns', sa.Boolean(), nullable=False),
    sa.Column('orientation', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('signature', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sheet_definition_id'], ['sheet_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_definitions_sheet_definition_id'), 'table_definitions', ['sheet_definition_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('file_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('error_log', sa.JSON(), nullable=False),
    sa.Column('requested_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_version_id'], ['country_file_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_file_version_id'), 'analysis_jobs', ['file_version_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_organization_id'), 'analysis_jobs', ['organization_id'], unique=False)
    op.create_table('table_column_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('table_definition_id', sa.String(length=36), nullable=False),
    sa.Column('excel_column', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['table_definition_id'], ['table_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_definition_id', 'excel_column')
    )
    op.create_index(op.f('ix_table_column_definitions_table_definition_id'), 'table_column_definitions', ['table_definition_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_job_id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('file_version_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('table_definition_id', sa.String(length=36), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected', sa.JSON(), nullable=True),
    sa.Column('actual', sa.JSON(), nullable=True),
    sa.Column('expected_coordinates', sa.String(length=100), nullable=True),
    sa.Column('actual_coordinates', sa.String(length=100), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('match_reasons', sa.JSON(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('expected_preview', sa.JSON(), nullable=True),
    sa.Column('actual_preview', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['file_version_id'], ['country_file_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['table_definition_id'], ['table_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_analysis_job_id'), 'anomalies', ['analysis_job_id'], unique=False)
    op.create_index(op.f('ix_anomalies_category'), 'anomalies', ['category'], unique=False)
    op.create_index(op.f('ix_anomalies_country_id'), 'anomalies', ['country_id'], unique=False)
    op.create_index(op.f('ix_anomalies_file_version_id'), 'anomalies', ['file_version_id'], unique=False)
    op.create_index('ix_anomalies_filters', 'anomalies', ['organization_id', 'category', 'severity', 'status'], unique=False)
    op.create_index(op.f('ix_anomalies_organization_id'), 'anomalies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_index(op.f('ix_anomalies_sheet_name'), 'anomalies', ['sheet_name'], unique=False)
    op.create_index(op.f('ix_anomalies_table_definition_id'), 'anomalies', ['table_definition_id'], unique=False)
    op.create_table('extracted_tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_job_id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('table_definition_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('source_range', sa.String(length=100), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('cell_coordinates', sa.JSON(), nullable=False),
    sa.Column('formulas', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['table_definition_id'], ['table_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_tables_analysis_job_id'), 'extracted_tables', ['analysis_job_id'], unique=False)
    op.create_index(op.f('ix_extracted_tables_country_id'), 'extracted_tables', ['country_id'], unique=False)
    op.create_index(op.f('ix_extracted_tables_table_definition_id'), 'extracted_tables', ['table_definition_id'], unique=False)
    op.create_table('anomaly_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('anomaly_id', sa.String(length=36), nullable=False),
    sa.Column('previous_status', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_decisions_anomaly_id'), 'anomaly_decisions', ['anomaly_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_decisions_anomaly_id'), table_name='anomaly_decisions')
    op.drop_table('anomaly_decisions')
    op.drop_index(op.f('ix_extracted_tables_table_definition_id'), table_name='extracted_tables')
    op.drop_index(op.f('ix_extracted_tables_country_id'), table_name='extracted_tables')
    op.drop_index(op.f('ix_extracted_tables_analysis_job_id'), table_name='extracted_tables')
    op.drop_table('extracted_tables')
    op.drop_index(op.f('ix_anomalies_table_definition_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_sheet_name'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_organization_id'), table_name='anomalies')
    op.drop_index('ix_anomalies_filters', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_file_version_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_country_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_category'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_analysis_job_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_table_column_definitions_table_definition_id'), table_name='table_column_definitions')
    op.drop_table('table_column_definitions')
    op.drop_index(op.f('ix_analysis_jobs_organization_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_file_version_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_table_definitions_sheet_definition_id'), table_name='table_definitions')
    op.drop_table('table_definitions')
    op.drop_index(op.f('ix_country_file_versions_sha256'), table_name='country_file_versions')
    op.drop_index(op.f('ix_country_file_versions_country_file_id'), table_name='country_file_versions')
    op.drop_table('country_file_versions')
    op.drop_index(op.f('ix_sheet_definitions_template_version_id'), table_name='sheet_definitions')
    op.drop_table('sheet_definitions')
    op.drop_index(op.f('ix_country_files_country_id'), table_name='country_files')
    op.drop_table('country_files')
    op.drop_index(op.f('ix_template_versions_template_id'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_sha256'), table_name='template_versions')
    op.drop_table('template_versions')
    op.drop_index(op.f('ix_countries_template_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_organization_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_consolidated_workbooks_consolidation_job_id'), table_name='consolidated_workbooks')
    op.drop_table('consolidated_workbooks')
    op.drop_index(op.f('ix_templates_organization_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_consolidation_jobs_organization_id'), table_name='consolidation_jobs')
    op.drop_table('consolidation_jobs')
    op.drop_index('ix_audit_org_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
